### ISSUE TITLE
cannot install GUI

### ISSUE THREAD

**Issue by vpnydv10year** [xybu/onedrive-d#17]
I've finished with first command in install with no GUI support
but now
when I run 
"$ python3 setup.py install gui " 
it shows rhis 
'in module'

vipin@vpn:~/Applications/onedrive-d-master$ sudo python3 setup.py install gui
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    from setuptools import setup
  File "/usr/local/lib/python3.4/dist-packages/setuptools/__init__.py", line 11, in <module>
    from setuptools.extension import Extension
  File "/usr/local/lib/python3.4/dist-packages/setuptools/extension.py", line 8, in <module>
    from .dist import _get_unpatched
  File "/usr/local/lib/python3.4/dist-packages/setuptools/dist.py", line 21, in <module>
    packaging = pkg_resources.packaging
AttributeError: 'module' object has no attribute 'packaging'
vipin@vpn:~/Applications/onedrive-d-master$

**Comment by xybu** [comment]
#15
