### ISSUE TITLE
WhT

### ISSUE THREAD

**Issue by SantiBrieva** [xybu/onedrive-d#38]
sudo python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    from setuptools import setup, find_packages
  File "/usr/local/lib/python3.4/dist-packages/setuptools/__init__.py", line 11, in <module>
    from setuptools.extern.six.moves import filterfalse, map
  File "/usr/local/lib/python3.4/dist-packages/setuptools/extern/__init__.py", line 1, in <module>
    from pkg_resources.extern import VendorImporter
ImportError: No module named 'pkg_resources.extern'

**Comment by viniciostorres** [comment]
Same in the old version. I can't use any version...

**Comment by xybu** [comment]
Update your python3-setuptools package. Assuming you have pip:

```
$ pip install -U pip
$ pip3 install -U setuptools
```

**Comment by bernardolm** [comment]
Same error, @xybu this solution doesn't work :(
