### ISSUE TITLE
Onedrived halts with error

### ISSUE THREAD

**Issue by viniciostorres** [xybu/onedrive-d#42]
I have installed onedrived on Ubuntu 14.04. I have configured and executed ondrived. The sync starts but soon halts with the error showed after:

`[2016-02-17 23:05:32,955] (DEBUG) W1: "GET /y3md--zHxpgt1zC-J0Dzg_Xah4AS6sqyeLRW45niMfkkWh-vOEmSNEq_FGBBhJ62-3Tte5ux1kqSaVK21XXXXXXXXXXXXXXXXXX0Gb-TS2OjcD7fG5OcbtrEEBYOku59Q7lbtaKdyS7WV6L7iMykWZhZCCkVb39an1MAUOkM/Curr%C3%ADculo%20Sandra%20(2).doc HTTP/1.1" 200 4214
[2016-02-17 23:05:33,133] (DEBUG) W1: Acquired task of type "DownloadFileTask" on parent "/home/sandra/OneDrive/", name "Currículo Sandra.odt".
[2016-02-17 23:05:33,140] (DEBUG) W1: Setting read timeout to None
Exception in thread W0:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.4/dist-packages/onedrived-2.0.0-py3.4.egg/onedrived/common/task_worker.py", line 27, in run
    task.handle()
  File "/usr/local/lib/python3.4/dist-packages/onedrived-2.0.0-py3.4.egg/onedrived/common/tasks/down_task.py", line 35, in handle
    self.items_store.update_item(self._item, ItemRecordStatuses.DOWNLOADED)
  File "/usr/local/lib/python3.4/dist-packages/onedrived-2.0.0-py3.4.egg/onedrived/store/items_db.py", line 159, in update_item
    (item.id, item.type, item.name, parent_ref.id, parent_path, item.e_tag, item.c_tag,
  File "/usr/local/lib/python3.4/dist-packages/onedrived-2.0.0-py3.4.egg/onedrived/api/items.py", line 103, in c_tag
    return self._data['cTag'] if 'eTag' in self._data else None
KeyError: 'cTag'

**Comment by xybu** [comment]
Don't use this repo yet. A few core components not ready. Probably try the onedrive-d-old repo...
I saw a bug though... Thanks for the report!
