### ISSUE TITLE
is there a bug in "4 View / Edit / Delete existing Drivers"

### ISSUE THREAD

**Issue by gameboy709494** [xybu/onedrive-d#48]
I just setup up  onedrive link and want to configure it by using `onedrived-pref`.

But after typing the _command_ for  _List registered Drives for editing / deleting_, I always get error  message about "_IndexError: list index out of range_".

```
List registered Drives for editing / deleting...

 >  To edit a Drive, type the index of the Drive in the table.
 >  To delete a Drive, type a minus sign followed by the index of the Drive.
 >  To abort and return to main menu, hit [Ctrl+C].
 >  For example, type "1" to edit the Drive indexed 1, and type "-1" to delete it.


Please enter command: 0
Traceback (most recent call last):
  File "/usr/local/bin/onedrived-pref", line 9, in <module>
    load_entry_point('onedrived==2.0.0', 'console_scripts', 'onedrived-pref')()
  File "/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrived/cli/pref_main.py", line 447, in main
    prompt_task()
  File "/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrived/cli/pref_main.py", line 441, in prompt_task
    dispatch_task()
  File "/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrived/cli/pref_main.py", line 421, in dispatch_task
    tasks[task_id]()
  File "/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrived/cli/pref_main.py", line 276, in list_existing_drives
    prompt_edit_drive(drive_list)
  File "/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrived/cli/pref_main.py", line 235, in prompt_edit_drive
    drive = drive_list[target_id]
IndexError: list index out of range
```

I only setup up one onedrive link, and `onedrived-pref`'s "_View / Delete connected OneDrive accounts_" tells it's _index_ is _0_. 

Here is detail, and I changed my Account ID to _xxx_:
```
$ onedrived-pref 
==================================================
=          onedrive-d Preference Wizard          =
==================================================

System Information
User name                      chen                                                                                                  
Configuration path             /home/chen/.onedrived                                                                                 

--------------------------------------------------------------------------------

Preference wizard supports the following tasks:

[0] Connect a new OneDrive Personal Account
[1] Connect a new OneDrive for Business Account
[2] View / Delete connected OneDrive accounts
[3] Add a remote Drive to sync
[4] View / Edit / Delete existing Drives
[5] Edit global ignore list files
[6] Edit HTTPS proxies
[7] Configure synchronization workload (resync interval, etc.)
[8] Exit wizard

Please enter the task index and hit [ENTER]: 2

--------------------------------------------------------------------------------

You have linked the following account(s) to onedrive-d:

Index      Account ID           Account Type         Name                                                                          
0          c16e8437649xxxxx     personal                                                                                           

To delete an account, type the index and hit [Enter]. Otherwise hit [Ctrl+C] to break.
Note: all the Drives belonging to the account will also be deleted.

Type the index of the account to delete: ^CAborted.

--------------------------------------------------------------------------------

Preference wizard supports the following tasks:

[0] Connect a new OneDrive Personal Account
[1] Connect a new OneDrive for Business Account
[2] View / Delete connected OneDrive accounts
[3] Add a remote Drive to sync
[4] View / Edit / Delete existing Drives
[5] Edit global ignore list files
[6] Edit HTTPS proxies
[7] Configure synchronization workload (resync interval, etc.)
[8] Exit wizard

Please enter the task index and hit [ENTER]: 4

--------------------------------------------------------------------------------

List registered Drives for editing / deleting...

 >  To edit a Drive, type the index of the Drive in the table.
 >  To delete a Drive, type a minus sign followed by the index of the Drive.
 >  To abort and return to main menu, hit [Ctrl+C].
 >  For example, type "1" to edit the Drive indexed 1, and type "-1" to delete it.


Please enter command: 0
Traceback (most recent call last):
  File "/usr/local/bin/onedrived-pref", line 9, in <module>
    load_entry_point('onedrived==2.0.0', 'console_scripts', 'onedrived-pref')()
  File "/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrived/cli/pref_main.py", line 447, in main
    prompt_task()
  File "/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrived/cli/pref_main.py", line 441, in prompt_task
    dispatch_task()
  File "/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrived/cli/pref_main.py", line 421, in dispatch_task
    tasks[task_id]()
  File "/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrived/cli/pref_main.py", line 276, in list_existing_drives
    prompt_edit_drive(drive_list)
  File "/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrived/cli/pref_main.py", line 235, in prompt_edit_drive
    drive = drive_list[target_id]
IndexError: list index out of range
```

And I tried _1_, 
```
$ onedrived-pref 
==================================================
=          onedrive-d Preference Wizard          =
==================================================

System Information
Configuration path             /home/chen/.onedrived                                                                                 
User name                      chen                                                                                                  

--------------------------------------------------------------------------------

Preference wizard supports the following tasks:

[0] Connect a new OneDrive Personal Account
[1] Connect a new OneDrive for Business Account
[2] View / Delete connected OneDrive accounts
[3] Add a remote Drive to sync
[4] View / Edit / Delete existing Drives
[5] Edit global ignore list files
[6] Edit HTTPS proxies
[7] Configure synchronization workload (resync interval, etc.)
[8] Exit wizard

Please enter the task index and hit [ENTER]: 4

--------------------------------------------------------------------------------

List registered Drives for editing / deleting...

 >  To edit a Drive, type the index of the Drive in the table.
 >  To delete a Drive, type a minus sign followed by the index of the Drive.
 >  To abort and return to main menu, hit [Ctrl+C].
 >  For example, type "1" to edit the Drive indexed 1, and type "-1" to delete it.


Please enter command: 1
Traceback (most recent call last):
  File "/usr/local/bin/onedrived-pref", line 9, in <module>
    load_entry_point('onedrived==2.0.0', 'console_scripts', 'onedrived-pref')()
  File "/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrived/cli/pref_main.py", line 447, in main
    prompt_task()
  File "/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrived/cli/pref_main.py", line 441, in prompt_task
    dispatch_task()
  File "/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrived/cli/pref_main.py", line 421, in dispatch_task
    tasks[task_id]()
  File "/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrived/cli/pref_main.py", line 276, in list_existing_drives
    prompt_edit_drive(drive_list)
  File "/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrived/cli/pref_main.py", line 235, in prompt_edit_drive
    drive = drive_list[target_id]
IndexError: list index out of range
```

It just keep telling me _list index out of range_ ...

**Comment by gameboy709494** [comment]
Oh, I forget tell you guys about my envirement:
```
$ uname -a
Linux RaspberryPi-2 4.3.3-v7+ #11 SMP PREEMPT Mon Mar 7 18:37:23 CST 2016 armv7l armv7l armv7l GNU/Linux
cat /etc/issue
Ubuntu Xenial Xerus (development branch) \n \l
```
