### ISSUE TITLE
Error on onedrived

### ISSUE THREAD

**Issue by eversonpiza** [xybu/onedrive-d#56]
Hi,

My onedrived was working fine, but after a few hour they became do get the error below.

everson@everson-linux:~$ onedrived
[2016-04-19 22:32:21,991] (DEBUG) W0: Started.
[2016-04-19 22:32:21,991] (DEBUG) W1: Started.
[2016-04-19 22:32:21,991] (INFO) MainThread: Refilling initial tasks...
[2016-04-19 22:32:21,992] (DEBUG) W0: Acquired task of type "MergeDirTask" on parent "/l/disk0/everson/OneDrive", name "".
[2016-04-19 22:32:21,999] (INFO) W0: Starting new HTTPS connection (1): api.onedrive.com
[2016-04-19 22:32:22,562] (DEBUG) W0: Setting read timeout to None
[2016-04-19 22:32:22,979] (DEBUG) W0: "GET /v1.0/drives/c7729e052b513cd/root:/:/children HTTP/1.1" 200 1309
[2016-04-19 22:32:22,982] (INFO) W0: Fix database record for directory "/l/disk0/everson/OneDrive/Casa".
[2016-04-19 22:32:23,087] (INFO) W0: Fix database record for directory "/l/disk0/everson/OneDrive/Documentos".
[2016-04-19 22:32:23,179] (INFO) W0: Fix database record for directory "/l/disk0/everson/OneDrive/Imagens".
[2016-04-19 22:32:23,280] (INFO) W0: Fix database record for directory "/l/disk0/everson/OneDrive/Jogos".
[2016-04-19 22:32:23,390] (INFO) W0: Fix database record for directory "/l/disk0/everson/OneDrive/Música".
[2016-04-19 22:32:23,482] (INFO) W0: Fix database record for directory "/l/disk0/everson/OneDrive/Particular".
[2016-04-19 22:32:23,574] (INFO) W0: Fix database record for directory "/l/disk0/everson/OneDrive/Tmp".
[2016-04-19 22:32:23,666] (INFO) W0: Fix database record for directory "/l/disk0/everson/OneDrive/Trabalho".
Exception in thread W0:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.4/dist-packages/onedrived-2.0.0-py3.4.egg/onedrived/common/task_worker.py", line 27, in run
    task.handle()
  File "/usr/local/lib/python3.4/dist-packages/onedrived-2.0.0-py3.4.egg/onedrived/common/tasks/merge_task.py", line 61, in handle
    self._analyze_local_item(local_item_name)
  File "/usr/local/lib/python3.4/dist-packages/onedrived-2.0.0-py3.4.egg/onedrived/common/tasks/merge_task.py", line 254, in _analyze_local_item
    self._create_upload_task(local_item_name, is_dir)
  File "/usr/local/lib/python3.4/dist-packages/onedrived-2.0.0-py3.4.egg/onedrived/common/tasks/merge_task.py", line 266, in _create_upload_task
    self._create_remote_dir(local_item_name)
  File "/usr/local/lib/python3.4/dist-packages/onedrived-2.0.0-py3.4.egg/onedrived/common/tasks/merge_task.py", line 279, in _create_remote_dir
    new_item = self.drive.create_dir(name=name, parent_path=self.remote_path)
  File "/usr/local/lib/python3.4/dist-packages/onedrived-2.0.0-py3.4.egg/onedrived/api/drives.py", line 202, in create_dir
    request = self.root.account.session.post(uri, json=data, ok_status_code=requests.codes.created)
  File "/usr/local/lib/python3.4/dist-packages/onedrived-2.0.0-py3.4.egg/onedrived/api/restapi.py", line 111, in post
    return self.request('post', url, params, ok_status_code=ok_status_code, auto_renew=auto_renew)
  File "/usr/local/lib/python3.4/dist-packages/onedrived-2.0.0-py3.4.egg/onedrived/api/restapi.py", line 46, in request
    request = getattr(self.session, method)(url, **params)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 497, in post
    return self.request('POST', url, data=data, **kwargs)
TypeError: request() got an unexpected keyword argument 'json'

Can anybody help me?

Thanks

**Comment by apmon** [comment]
I am running into the same issue with the exception thrown of "TypeError: request() got an unexpected keyword argument 'json'"

It looks like it might be an issue with having a too old python requests package installed. If I see it correctly the json functionality was added in requests version 2.4.3[1].

In my case, I have requests version 2.2.1 installed. The problem is that I can't update the requests package, because it wasn't installed by pip, but through the operating system packaging system apt (Ubuntu 14.04) and Ubuntu isn't supplying an update package.  


[1] http://www.coglib.com/~icordasc/blog/2014/11/sending-json-in-requests.html

**Comment by eversonpiza** [comment]
I give up on onedrived, now I'm using onedrive web.
