### ISSUE TITLE
AttributeError: 'ItemRecord' object has no attribute 'is_folder'

### ISSUE THREAD

**Issue by AnyOldName3** [xybu/onedrive-d#71]
Hi.

I'll preface this by pointing out that I'm using the dev branch of @tobecontinued 's fork of this, but that doesn't have its own issue tracker, and it may well apply here, too.

I'm seeing an exception thrown while 'Fix[ing] database record for file ...'. Here's the stack trace:

```python
Exception in thread W3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrived/common/task_worker.py", line 27, in run
    task.handle()
  File "/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrived/common/tasks/merge_task.py", line 61, in handle
    self._analyze_local_item(local_item_name)
  File "/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrived/common/tasks/merge_task.py", line 248, in _analyze_local_item
    if item.is_folder != is_dir:
AttributeError: 'ItemRecord' object has no attribute 'is_folder'
```

At the time this is thrown, onedrived ceases to do anything, even though it's not fully synchronised - there a bunch of files it's not deleted, even though they're gone from the canonical version of my onedrive.

In case it makes a difference, I was using this version of OneDrive-D, but then switched to the fork my changing the git remote, pulling, and rerunning setup.py in both build and install mode.

**Comment by tobecontinued** [comment]
sorry, there is a typo.
```python
 if item.is_folder != is_dir:
```
it should be 
```python
 if item_is_folder != is_dir
```
I will fix it soon

**Comment by tobecontinued** [comment]
I fix it @AnyOldName3 . thank you for your feedback.
