### ISSUE TITLE
JSON Decode Error

### ISSUE THREAD

**Issue by AnyOldName3** [xybu/onedrive-d#72]
Hi again. As in my last issue report, I'm using tobecontinued's fork, having just done a git pull and rebuild/reinstall right before getting this problem.

Upon receiving an UploadFileTask, the following exception was thrown and stack trace printed:

```python
Exception in thread W1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrived/common/task_worker.py", line 27, in run
    task.handle()
  File "/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrived/common/tasks/up_task.py", line 51, in handle
    conflict_behavior=self._conflict_behavior)
  File "/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrived/api/drives.py", line 218, in upload_file
    return self.put_file(filename, data, parent_id, parent_path, conflict_behavior)
  File "/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrived/api/drives.py", line 283, in put_file
    request = self.root.account.session.put(uri, data=data, ok_status_code=requests.codes.created)
  File "/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrived/api/restapi.py", line 145, in put
    ok_status_code=ok_status_code, auto_renew=auto_renew)
  File "/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrived/api/restapi.py", line 58, in request
    raise errors.OneDriveError(request.json())
  File "/usr/lib/python3/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I'm hoping this is enough to identify the cause. The only symptom other than the stack trace is that the program stops printing anything, until the 'refilling initial tasks' message is due.

**Comment by tobecontinued** [comment]
this bug also happens when I use it, But I am focusing on other bugs right now.
